version: '3.3'

services:
  vscode:
    container_name: 'vscode'
    build:
      context: .docker/vscode
    restart: always
    ports:
      - "${PORT}:8080"
    volumes:
      - "<dir>:/home/coder/project" #改成你的文件夹路径
    environment:
      PASSWORD: ${PASSWORD}
